version: '3.8'
services:
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - PORT=8001
    command:
      sh -c 'npm ci && node index.js'

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379